#inherit_from: /.rubocop.yml

AllCops:
  Exclude:
    - db_deserializers/schema.rb

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Metrics/LineLength:
  Max: 120

# Checks for %q/%Q when single quotes or double quotes would do.
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

