:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
development:
  :concurrency: 5
production:
  :concurrency: 1
:queues:
  - critical
  - default
  - low

:schedule:
  snp500_companies:
    cron: '0 20 * * 1-5 America/New_York'   # Runs every week-day at 8PM ET
    class: Snp500Worker
    description: "Save S & P 500 Companies every week-day at 8PM ET"
